### ISSUE TITLE
[Enhancement] Refactor dart_style directly?

### ISSUE THREAD

**Issue by rainyl** [eggnstone/dart_format#6]
I noticed that the formatter of dart is located in [dart_style](https://github.com/dart-lang/dart_style), actually it provides many options but most of them are hidden, https://github.com/dart-lang/dart_style/blob/6570b94562e7093e4b4f1ac7b59b5056ffe933a3/lib/src/cli/options.dart#L87C3-L103C4 , so maybe refactor dart_style to allow configurations may be a more convenient and time-saving way?

**Comment by eggnstone** [comment]
Valid idea, but I guess it would mean to do a lot of work again for the additional formatting that I want. I think I'm more flexible now that my formatter basically works.
